
LOCAL_PATH:= $(call my-dir)
#LOCAL_C_INCLUDES := $(LOCAL_PATH)

include $(CLEAR_VARS)

LOCAL_MODULE    := libnet
LOCAL_CFLAGS += $(GLOBAL_CFLAGS)
LOCAL_C_INCLUDES += $(GLOBAL_C_INCLUDES)
LOCAL_SRC_FILES :=  _net.cpp

LOCAL_STATIC_LIBRARIES := minilzo

include $(BUILD_STATIC_LIBRARY)
